services:
  remnanode:
    container_name: remnanode
    image: remnawave/node:latest
    restart: always
    environment:
      - NODE_PORT=2222
      - SECRET_KEY=${NODE_SECRET_KEY}
    ports:
      - "2222:2222"
    networks:
      - remnawave-network

  remnawave-subscription-page:
    image: remnawave/subscription-page:latest
    container_name: remnawave-subscription-page
    restart: always
    environment:
      - APP_PORT=3010
      - APP_HOST=0.0.0.0
      - REMNAWAVE_PANEL_URL=${PANEL_URL}
      - REMNAWAVE_API_TOKEN=${REMNAWAVE_API_TOKEN}
      - NODE_ENV=development
      - TRUST_PROXY=true
    networks:
      - remnawave-network

  caddy:
    image: caddy:2.9
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SUB_DOMAIN=${SUB_DOMAIN}      # Динамический домен подписок
      - CABINET_DOMAIN=${CABINET_DOMAIN} # Динамический домен кабинета
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-ssl-data:/data
      - ./cabinet:/var/www/cabinet:ro
    networks:
      - remnawave-network

networks:
  remnawave-network:
    name: remnawave-network
    driver: bridge

volumes:
  caddy-ssl-data: