services:
  remnanode:
    container_name: remnanode
    image: remnawave/node:2.6.1
    restart: always
    environment:
      - NODE_PORT=2222
      - SECRET_KEY=${NODE_SECRET_KEY}
    ports:
      - "${NODE_IP}:2222:2222" # Привязка к IP ноды
      - "${NODE_IP}:443:443"
    networks:
      - remnawave-network

  remnawave-subscription-page:
    image: remnawave/subscription-page:7.1.8
    container_name: remnawave-subscription-page
    restart: always
    environment:
      - APP_PORT=3010
      - APP_HOST=0.0.0.0
      - REMNAWAVE_PANEL_URL=${PANEL_URL}
      - REMNAWAVE_API_TOKEN=${REMNAWAVE_API_TOKEN}
      - NODE_ENV=development
      - TRUST_PROXY=true
    networks:
      - remnawave-network

  caddy:
    image: caddy:2.9
    container_name: caddy
    restart: always
    ports:
      - "${NODE_IP}:80:80"
      - "${NODE_IP}:${SUB_PORT}:443"
    environment:
      - SUB_DOMAIN=${SUB_DOMAIN}      
      - CABINET_DOMAIN=${CABINET_DOMAIN} 
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - ./cabinet:/var/www/cabinet:ro
    networks:
      - remnawave-network

networks:
  remnawave-network:
    name: remnawave-network
    driver: bridge

volumes:
  caddy-data:
    name: caddy-data